# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69fd236ffad8aeb5bf8cf034b31c4bae2b19075299a862bd214ed2b3a261cc92c894381b78145773f900ed97af3edf83a84014121c06f2eda5d1b1a680ef3afe

test:
  secret_key_base: d957a02d7c38b397882ee1dc9028c8b51a12bd11b60c2480800bb8e9d39274dae9954e8ad8377dbb4daa1eea1b58dafe5aa278d5bedebd9eb037b00bcfb08cfe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
